from torch import nn as nn

# Following DCGANGenerator is a fork from the Pytorch tutorial:
# https://pytorch.org/tutorials/beginner/dcgan_faces_tutorial.html

class DCGANGenerator(nn.Module):
    """
    A Generator class for the type DCGAN.
    """

    def __init__(self, ngpu, latent_vector_size, ftr_map_size_gn, op_chnls, bias=False) -> None:
        """
        Init function to create a DCGAN generator object.

        This function initializes a Sequential which is used during the forward function.

        Keyword Arguments:
        ngpu: Number of GPUs available
        latent_vector_size: the size of the vector from which the fake image will be generated
        ftr_map_size_gn: depth of the generator output feature map
        op_chnls: number of output image channels
        bias: bias value for batch norm
        """
        super(DCGANGenerator).__init__()
        self.ngpu = ngpu
        self.main = nn.Sequential(
            nn.ConvTranspose2d(latent_vector_size, ftr_map_size_gn * 8, 4, 1, 0, bias = bias),
            nn.BatchNorm2d(ftr_map_size_gn*8),
            nn.ReLU(True),

            nn.ConvTranspose2d(ftr_map_size_gn * 8, ftr_map_size_gn * 4, 4, 2, 1, bias = bias),
            nn.BatchNorm2d(ftr_map_size_gn * 4),
            nn.ReLU(True),

            nn.ConvTranspose2d(ftr_map_size_gn * 4, ftr_map_size_gn * 2, 4, 2, 1, bias = bias),
            nn.BatchNorm2d(ftr_map_size_gn * 2),
            nn.ReLU(True),

            nn.ConvTranspose2d(ftr_map_size_gn * 2, ftr_map_size_gn, 4, 2, 1, bias = bias),
            nn.BatchNorm2d(ftr_map_size_gn),
            nn.ReLU(True),

            nn.ConvTranspose2d(ftr_map_size_gn, op_chnls, 4, 2, 1, bias = bias),
            nn.Tanh()
        )

    def forward(self, input):
        """
        Forward function of the DCGAN Generator object

        Keyword Arguments:
        input: the input from which the fake image has to be generated

        Returns:
        The fake image generated by the sequential created in __init__ function 
        """
        return self.main(input)